"""Stegosource chart theming for Plotly.

Provides a consistent dark-theme layout configuration for all Plotly charts
generated by the agent. Colors are derived from the design system.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Brand color constants
# ---------------------------------------------------------------------------

CHART_COLORS: list[str] = [
    "#00D4FF",  # Cyan (primary series)
    "#E040A0",  # Magenta
    "#00E676",  # Green
    "#FFB020",  # Amber
    "#8B5CF6",  # Violet
    "#F04848",  # Red
    "#06B6D4",  # Teal
    "#F59E0B",  # Orange
]
"""Sequential palette for multi-series charts, ordered for visual distinction."""

CANDLESTICK_UP: str = "#00E676"
"""Color for bullish (close > open) candlestick bars."""

CANDLESTICK_DOWN: str = "#E040A0"
"""Color for bearish (close < open) candlestick bars."""

# ---------------------------------------------------------------------------
# Plotly layout template
# ---------------------------------------------------------------------------

STEGO_LAYOUT: dict[str, Any] = {
    "paper_bgcolor": "rgba(0,0,0,0)",
    "plot_bgcolor": "rgba(0,0,0,0)",
    "font": {
        "family": "Source Sans Pro, sans-serif",
        "color": "#FAFAFA",
        "size": 13,
    },
    "title": {
        "font": {"size": 20, "color": "#FAFAFA"},
        "x": 0,
        "xanchor": "left",
    },
    "xaxis": {
        "gridcolor": "#333844",
        "zerolinecolor": "#333844",
        "tickfont": {"color": "#A0A8B8", "size": 12},
        "title": {"font": {"color": "#A0A8B8", "size": 13}},
    },
    "yaxis": {
        "gridcolor": "#333844",
        "zerolinecolor": "#333844",
        "tickfont": {"color": "#A0A8B8", "size": 12},
        "title": {"font": {"color": "#A0A8B8", "size": 13}},
    },
    "legend": {
        "font": {"color": "#A0A8B8", "size": 12},
        "bgcolor": "rgba(0,0,0,0)",
    },
    "hoverlabel": {
        "bgcolor": "#262A36",
        "font_size": 13,
        "font_color": "#FAFAFA",
        "bordercolor": "#333844",
    },
    "colorway": CHART_COLORS,
    "margin": {"l": 48, "r": 24, "t": 56, "b": 48},
}
"""Plotly layout configuration matching the Stegosource dark theme.

Usage::

    import plotly.express as px
    from chart_theme import STEGO_LAYOUT

    fig = px.line(data, x="date", y="close", title="AAPL closing price")
    fig.update_layout(**STEGO_LAYOUT)
    st.plotly_chart(fig, width="stretch")
"""
